from .birth import *
from .death import *
from .geoplace import *
from .parent import *
from .person import *
from .confession import *
from .religion import *
from .occupation_peit import *
from .occupation_teen import *
